### ISSUE TITLE
Display error message

### ISSUE THREAD

**Issue by cclough715** [ProjectCollaboTeam/Collab#10]
When a user clicks the ask tab when they're not registered for classes there should be some text letting them know they're not enrolled in any courses

**Comment by cclough715** [comment]
Similarly, if there are no favorite or trending questions we should let the user know

**Comment by Tyler8oliver** [comment]
closed

**Comment by cclough715** [comment]
Similar to before, if a user goes to remove a class when he/she is not enrolled in any courses we should provide feedback
