### ISSUE TITLE
Get file uploads working

### ISSUE THREAD

**Issue by Tyler8oliver** [ProjectCollaboTeam/Collab#4]
do that shit yo

**Comment by Tyler8oliver** [comment]
Theres a user/photo route that allows a user to upload there profile photo. It'd be awesome if someone can do this

**Comment by Tyler8oliver** [comment]
In the client, validate that the filetype is an image (png, jpg, gif)
Once uploaded to the server, store the file in the directory, /public/images/uploads/user/:user_id/'thefilename';
and then run this sql command;
'UPDATE users
SET avatar = '+/images/uploads/user/'+req.session.data.id+'/'+filename '
'WHERE id = '+req.session.data.id;
user_id is found in req.session.data.id

**Comment by myimedia** [comment]
@Tyler8oliver , run mysqldump > db.sql and add the file to the repo.

**Comment by Tyler8oliver** [comment]
ok

**Comment by myimedia** [comment]
The file stream reader is configured and working. Images received and saved. app.js updates the profile image with the response from the server.

TODO: Fix SQL Query that stores filepath
TODO: Query for image and update img src on page entry.
